name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Install Package with docs extra
        run: |
         pip install .[docs]

      - name: List dependencies
        run: pip freeze

      - name: Setup Envvars
        run: |
            if [[ $GITHUB_REF = "refs/tags/"* ]] ; then echo "CUTQC_VERSION=${GITHUB_REF/refs\/tags\//}" ; else echo "CUTQC_VERSION=" ; fi >> $GITHUB_ENV

      - name: Build docs
        run: |
          # Unless we add a .nojekyll to the base of the deployment folder, the underscores in foldernames
          # like _static/ etc. pose problems on GH Pages.
          cd docs && sphinx-apidoc -f -o source/src ../src/cutqc2 -H Modules && make html && touch build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          branch: gh-pages
